version: '3.8'

services:
  mini_tree:
    image: sifnoc/summa-aggregation:mini-tree-v0.1
    ports: # This does not effect to `CloudSpawner` configuration
      - target: 4000
      - published: 4000
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - mini_tree_net

networks:
  mini_tree_net:
    driver: overlay
